## 0. 파이썬에서의 복사는 메모리 구조를 가리킴

연산이 느릴 수 밖에 없음

In [1]:
a = [1,2,3,4,5]
b = a
b[2] = 5
a

[1, 2, 5, 4, 5]

In [2]:
b = a[:]
b[0] = 5
a

[1, 2, 5, 4, 5]

## 넘파이는 바로 숫자를 쌓는 식

파이썬보다 훨씬 빠름

In [3]:
import numpy as np

In [4]:
test_array = np.array(["1","4",5,8], float)
test_array

array([1., 4., 5., 8.])

In [6]:
test_array.dtype

dtype('float64')

.

# 1. shape

### <span style="color:red">vector일 때에는 세로로 한 줄로 인식  =>  튜플 형태로 (값 개수,)</span>

In [14]:
test_array = np.array(["1","4",5,8], np.float32)
test_array.shape

(4,)

In [9]:
test_array = np.array([["1","4",5,8]], np.float32)
test_array

array([[1., 4., 5., 8.]], dtype=float32)

In [10]:
test_array.shape

(1, 4)

### <span style="color:red">matrix -> (행, 열)</span>

In [22]:
matrix = [[1,2,3,4],[2,3,4,5],[3,4,5,6]]
np.array(matrix, int).shape

(3, 4)

### <span style="color:red">3차원 -> (깊이, 열, 행)</span>

In [19]:
tensor = [[[1,2,3,4],
           [2,3,4,5],
           [3,4,5,6]],
          
         [[1,2,3,4],
          [2,3,4,5],
          [3,4,5,6]],
          
         [[1,2,3,4],
          [2,3,4,5],
          [3,4,5,6]],
          
         [[1,2,3,4],
          [2,3,4,5],
          [3,4,5,6]]]

np.array(tensor, int).shape

(4, 3, 4)

.

## 2. ndim : dimension 수  /  size : data tn

In [20]:
tensor = [[[1,2,3,4],[2,3,4,5],[3,4,5,6]],
         [[1,2,3,4],[2,3,4,5],[3,4,5,6]],
         [[1,2,3,4],[2,3,4,5],[3,4,5,6]],
         [[1,2,3,4],[2,3,4,5],[3,4,5,6]]]
np.array(tensor, int).ndim

3

In [21]:
np.array(tensor, int).size

48

.

## 3. reshape

In [24]:
test_matrix = [[1,2,3,4], 
               [1,2,5,8]]
np.array(test_matrix).shape

(2, 4)

In [25]:
np.array(test_matrix).reshape(2,2,2)

array([[[1, 2],
        [3, 4]],

       [[1, 2],
        [5, 8]]])

### row의 개수는 모르지만, column의 개수를 특정짓고 싶을 때

In [26]:
np.array(test_matrix).reshape(-1,2)

array([[1, 2],
       [3, 4],
       [1, 2],
       [5, 8]])

### 다차원을 1차원 배열로 만들 때 : flatten()