In [2]:
import numpy as np

# 문제 시작

In [34]:
def n_size_ndarray_creation(n, dtype=np.int):
    return np.arange(n ** 2).reshape(n,2)

In [35]:
n_size_ndarray_creation(2)

array([[0, 1],
       [2, 3]])

In [30]:
def zero_or_one_or_empty_ndarray(shape, type=0, dtype=np.int):
    if type == 0:
        return np.zeros(shape=shape, dtype=dtype)
    elif type == 1:
        return np.ones(shape=shape, dtype=dtype)
    elif type == 99:
        return np.empty(shape=shape, dtype=dtype)

In [36]:
zero_or_one_or_empty_ndarray([2,3], 1)

array([[1, 1, 1],
       [1, 1, 1]])

In [42]:
def change_shape_of_ndarray(X, n_row):
    return X.reshape(n_row, -1)

In [46]:
X = np.ones((32,32), dtype=np.int)
change_shape_of_ndarray(X, 1)

array([[1, 1, 1, ..., 1, 1, 1]])

In [69]:
def concat_ndarray(X_1, X_2, axis):
    if X_1.ndim == 1:
        X1_col = X_1.shape[0]
        X1_row = 1
    else:
        X1_col = X_1.shape[1]
        X1_row = X_1.shape[0]
        
    if X_2.ndim == 1:
        X2_col = X_2.shape[0]
        X2_row = 1
    else:
        X2_col = X_2.shape[1]
        X2_row = X_2.shape[0]
        
    
    if axis == 0 and X_1.shape[1] != X_2.shape[1]:
        return False
    if axis == 1 and X_1.shape[0] != X_2.shape[0]:
        return False
    return np.concatenate((X_1, X_2), axis=axis)

In [65]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
concat_ndarray(a, b, 0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [58]:
concat_ndarray(a, b, 1)

False

In [76]:
a = np.array([[1, 2]])
b = np.array([[5, 6, 7]])
np.concatenate((a,b), 1)
# concat_ndarray(a, b, 1)


array([[1, 2, 5, 6, 7]])

In [41]:
def normalize_ndarray(X, axis=99, dtype=np.float32):
    if axis == 0:
        return [(X - X.mean(axis=0)) / X.std(axis=0)]
    elif axis == 1:
        return [(n - np.mean(n)) / np.std(n) for n in X]
    else:
        return [(X - X.mean()) / X.std()]

In [42]:
X = np.arange(12, dtype=np.float32).reshape(6,2)
X

array([[ 0.,  1.],
       [ 2.,  3.],
       [ 4.,  5.],
       [ 6.,  7.],
       [ 8.,  9.],
       [10., 11.]], dtype=float32)

In [43]:
normalize_ndarray(X)

[array([[-1.593255  , -1.3035723 ],
        [-1.0138896 , -0.7242068 ],
        [-0.4345241 , -0.14484136],
        [ 0.14484136,  0.4345241 ],
        [ 0.7242068 ,  1.0138896 ],
        [ 1.3035723 ,  1.593255  ]], dtype=float32)]

In [44]:
normalize_ndarray(X, 1)

[array([-1.,  1.], dtype=float32),
 array([-1.,  1.], dtype=float32),
 array([-1.,  1.], dtype=float32),
 array([-1.,  1.], dtype=float32),
 array([-1.,  1.], dtype=float32),
 array([-1.,  1.], dtype=float32)]

In [45]:
normalize_ndarray(X, 0)

[array([[-1.46385, -1.46385],
        [-0.87831, -0.87831],
        [-0.29277, -0.29277],
        [ 0.29277,  0.29277],
        [ 0.87831,  0.87831],
        [ 1.46385,  1.46385]], dtype=float32)]

In [46]:
def save_ndarray(X, filename="test.npy"):
    np.save(filename, arr=X)

In [48]:
X = np.arange(32, dtype=np.float32).reshape(4, -1)
filename = "test.npy"
save_ndarray(X, filename) #test.npy 파일이 생성됨

In [57]:
def boolean_index(X, condition):
    condition = eval(str("X") + condition)
    return X[condition]

In [58]:
X = np.arange(32, dtype=np.float32).reshape(4, -1)
boolean_index(X, "== 3")

array([3.], dtype=float32)

In [59]:
X = np.arange(32, dtype=np.float32)
boolean_index(X, "> 6")

array([ 7.,  8.,  9., 10., 11., 12., 13., 14., 15., 16., 17., 18., 19.,
       20., 21., 22., 23., 24., 25., 26., 27., 28., 29., 30., 31.],
      dtype=float32)

In [91]:
def find_nearest_value(X, target_value):
    return X[(np.abs(X - target_value)).argmin()]

In [95]:
X = np.random.uniform(0, 1, 100)
target_value = 0.3
find_nearest_value(X, target_value)

0.29561542113413886

In [101]:
def get_n_largest_values(X, n):
    X = np.sort(X)[::-1]
    return X[:n]

In [102]:
X = np.random.uniform(0, 1, 100)
get_n_largest_values(X, 3)

array([0.99851051, 0.99465147, 0.99271281])