In [1]:
import numpy as np

# 문제 시작

In [34]:
def n_size_ndarray_creation(n, dtype=np.int):
    return np.arange(n ** 2).reshape(n,2)

In [35]:
n_size_ndarray_creation(2)

array([[0, 1],
       [2, 3]])

In [30]:
def zero_or_one_or_empty_ndarray(shape, type=0, dtype=np.int):
    if type == 0:
        return np.zeros(shape=shape, dtype=dtype)
    elif type == 1:
        return np.ones(shape=shape, dtype=dtype)
    elif type == 99:
        return np.empty(shape=shape, dtype=dtype)

In [36]:
zero_or_one_or_empty_ndarray([2,3], 1)

array([[1, 1, 1],
       [1, 1, 1]])

In [42]:
def change_shape_of_ndarray(X, n_row):
    return X.reshape(n_row, -1)

In [46]:
X = np.ones((32,32), dtype=np.int)
change_shape_of_ndarray(X, 1)

array([[1, 1, 1, ..., 1, 1, 1]])

In [69]:
def concat_ndarray(X_1, X_2, axis):
    if X_1.ndim == 1:
        X1_col = X_1.shape[0]
        X1_row = 1
    else:
        X1_col = X_1.shape[1]
        X1_row = X_1.shape[0]
        
    if X_2.ndim == 1:
        X2_col = X_2.shape[0]
        X2_row = 1
    else:
        X2_col = X_2.shape[1]
        X2_row = X_2.shape[0]
        
    
    if axis == 0 and X_1.shape[1] != X_2.shape[1]:
        return False
    if axis == 1 and X_1.shape[0] != X_2.shape[0]:
        return False
    return np.concatenate((X_1, X_2), axis=axis)

In [65]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
concat_ndarray(a, b, 0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [58]:
concat_ndarray(a, b, 1)

False

In [76]:
a = np.array([[1, 2]])
b = np.array([[5, 6, 7]])
np.concatenate((a,b), 1)
# concat_ndarray(a, b, 1)


array([[1, 2, 5, 6, 7]])

In [ ]:




def normalize_ndarray(X, axis=99, dtype=np.float32):
    pass


def save_ndarray(X, filename="test.npy"):
    pass


def boolean_index(X, condition):
    pass


def find_nearest_value(X, target_value):
    pass


def get_n_largest_values(X, n):
    pass
