# mean & std

In [3]:
import numpy as np

In [3]:
test_array = np.arange(1,13).reshape(3,4)
test_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [4]:
test_array.mean()

6.5

In [5]:
test_array.mean(axis=0)

array([5., 6., 7., 8.])

In [6]:
test_array.std()

3.452052529534663

In [7]:
test_array.std(axis=0)

array([3.26598632, 3.26598632, 3.26598632, 3.26598632])

# concatenate 

좀 느림

In [14]:
a = np.array([1,2,3])
b = np.array([4,5,6])
np.vstack((a,b))

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
np.concatenate((a,b) , axis=0)

array([1, 2, 3, 4, 5, 6])

In [21]:
a = np.array([[1],
              [2],
              [3]])
b = np.array([[4],
              [5],
              [6]])
np.hstack((a,b))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [17]:
np.concatenate((a,b) , axis=1)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [18]:
test_a = np.array([[1,2,3],[4,5,6]], float)
test_a

array([[1., 2., 3.],
       [4., 5., 6.]])

In [19]:
test_a + test_a

array([[ 2.,  4.,  6.],
       [ 8., 10., 12.]])

In [20]:
test_a - test_a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [22]:
test_a * test_a

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

.

# transpose(), dot()

In [25]:
test_a = np.arange(1,7).reshape(2,3)
test_a

array([[1, 2, 3],
       [4, 5, 6]])

In [27]:
test_a.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [28]:
test_a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [32]:
test_a = np.arange(1,7).reshape(2,3)
test_b = np.arange(7,13).reshape(3,2)
test_a.dot(test_b)

array([[ 58,  64],
       [139, 154]])

In [35]:
test_a = np.arange(1,7).reshape(2,3)
test_b = np.arange(1,7).reshape(3,2)
print(test_a)
print(test_b)
test_a.dot(test_b)

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


array([[22, 28],
       [49, 64]])

# broadcasting

In [43]:
test_matrix = np.array([[1,2,3],[4,5,6]], float)
scalar = 3

test_matrix

array([[1., 2., 3.],
       [4., 5., 6.]])

In [44]:
test_matrix = np.array([[1,2,3],[4,5,6]], float)
scalar = 3

test_matrix + scalar

array([[4., 5., 6.],
       [7., 8., 9.]])

In [45]:
test_matrix = np.array([[1,2,3],[4,5,6]], float)
scalar = 3

test_matrix - scalar

array([[-2., -1.,  0.],
       [ 1.,  2.,  3.]])

In [46]:
test_matrix = np.array([[1,2,3],[4,5,6]], float)
scalar = 3

test_matrix * 5

array([[ 5., 10., 15.],
       [20., 25., 30.]])

In [5]:
test_matrix = np.array([[1,2,3],[4,5,6]], float)
scalar = 3

print(test_matrix / 0.2) # 좌항을 우항으로 나눔 (실수형)
print(test_matrix // 0.2) # 좌항을 우항으로 나눔 (정수형)

[[ 5. 10. 15.]
 [20. 25. 30.]]
[[ 4.  9. 14.]
 [19. 24. 29.]]


In [1]:
1 // 0.2  

4.0

# all & any

In [7]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
a > 5

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [10]:
np.any(a>5)

True

In [11]:
np.all(a>5)

False

.

# np.where()

In [13]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### 숫자가 5보다 크면 1, 아니면 0

In [14]:
np.where(a > 5, 1, 0)

array([0, 0, 0, 0, 0, 0, 1, 1, 1, 1])

In [38]:
np.where(a > 5)

(array([5, 6, 7, 8]),)

.

# argmax  & argmin

## 최대, 최소값의 인덱스를 반환한다.

In [27]:
a = np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
np.argmax(a)

8

In [29]:
np.argmin(a)

0

In [36]:
b = np.array([[1,9,3,21],
             [5,11,1,8],
             [9,21,11,12]])
np.argmax(b, axis=1)

array([3, 1, 1])

In [37]:
np.argmax(b, axis=0)

array([2, 2, 2, 0])

.

# boolean index

In [39]:
test_array = np.array([1,4,3,2,6,1,9,0], float)

In [40]:
test_array > 3

array([False,  True, False, False,  True, False,  True, False])

In [42]:
condition = test_array < 3
test_array[condition]

array([1., 2., 1., 0.])

In [53]:
A = np.array([
    [1,2,3,4,5,6,7,8,9],
    [1,2,3,4,5,6,7,8,9],
    [1,2,3,4,5,6,7,8,9],
    [1,2,3,4,5,6,7,8,9],
    [1,2,3,4,5,6,7,8,9],
    [1,2,3,4,5,6,7,8,9]
])

B = A < 5
B

array([[ True,  True,  True,  True, False, False, False, False, False],
       [ True,  True,  True,  True, False, False, False, False, False],
       [ True,  True,  True,  True, False, False, False, False, False],
       [ True,  True,  True,  True, False, False, False, False, False],
       [ True,  True,  True,  True, False, False, False, False, False],
       [ True,  True,  True,  True, False, False, False, False, False]])

In [54]:
B.astype(int)

array([[1, 1, 1, 1, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 0, 0, 0, 0, 0]])

.

# fancy index

In [44]:
a = np.array([2,4,6,8])
b = np.array([0,0,3,2,1], int)    # 반드시 integer로 선언
a.take(b)

array([2, 2, 8, 6, 4])

In [47]:
a = np.array([[1,4],
              [9,16]], float)
b = np.array([0,0,1,1,0], int)
c = np.array([0,1,1,1,1], int)
a[b,c]

array([ 1.,  4., 16., 16.,  4.])

.

# numpy object

In [49]:
a_int = np.arange(10)
np.save("npy_test", arr=a_int)

In [50]:
npy_array = np.load(file="npy_test.npy")

In [51]:
npy_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])