# 1. Indexing

In [1]:
import numpy as np

In [2]:
a = np.array([[1,2,3],
             [4.5,5,6]], int)
print(a)

[[1 2 3]
 [4 5 6]]


In [3]:
print(a[0,0]) # == a[0][0]

1


In [5]:
a[0,0] = 7
a

array([[7, 2, 3],
       [4, 5, 6]])

.

# 2. Slicing

In [10]:
a = np.array([[1,2,3,4,5], 
              [6,7,8,9,10]], int)
a[:, 2:]  # 전체 행, 2열부터

array([[ 3,  4,  5],
       [ 8,  9, 10]])

In [8]:
a[1,1:3] # 1행의 1~2열

array([7, 8])

In [9]:
a[1:3] # 1행 ~ 2행 전체

array([[ 6,  7,  8,  9, 10]])

.

# 3. Arange

In [12]:
np.arange(30)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [13]:
np.arange(0, 5, 0.5)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [14]:
np.arange(30).reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

.

# 4. zeros, ones

In [16]:
np.zeros(shape=(10,), dtype=np.int8)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int8)

In [17]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [19]:
np.ones(shape=(10,), dtype=np.int8)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int8)

In [20]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [22]:
test_matrix = np.arange(30).reshape(5,6)
np.ones_like(test_matrix)

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

.

# eye : 대각선으로 1인 행렬, k값으로 시작

In [23]:
np.eye(N=3, M=5, dtype=np.int8)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0]], dtype=int8)

In [24]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [25]:
np.eye(3,5,k=2)

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

.

# diag : 대각 행렬의 값을 추출함

In [27]:
matrix = np.arange(9).reshape(3,3)
print(matrix)
np.diag(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([0, 4, 8])

In [28]:
np.diag(matrix, k=1)

array([1, 5])

.

# random sampling

균등분포

In [29]:
np.random.uniform(0,1,10).reshape(2,5)

array([[0.95772478, 0.58641507, 0.00917061, 0.79416677, 0.73479445],
       [0.05706375, 0.11781452, 0.98698224, 0.10750058, 0.49034359]])

정규분포

In [32]:
np.random.normal(0,1,10).reshape(2,5)

array([[-1.58955919,  1.62503436,  0.56666   , -0.05023988,  0.00244338],
       [ 0.3534328 , -1.59528347,  0.09959157,  0.62051684, -0.09542587]])

.

# axis

In [34]:
test_array = np.arange(1,11)
test_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [36]:
test_array.sum(dtype=np.float)

55.0

In [37]:
test_array = np.arange(1,13).reshape(3,4)
test_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [38]:
test_array.sum(axis=1)

array([10, 26, 42])

In [39]:
test_array.sum(axis=0)

array([15, 18, 21, 24])