In [7]:
import pandas as pd
import numpy as np
from pandas import DataFrame

In [2]:
matrix = pd.read_csv('./movie_rating.csv')
matrix

source              target  rating
0   Jack Matthews   Lady in the Water     3.0
1   Jack Matthews   Snakes on a Plane     4.0
2   Jack Matthews   You Me and Dupree     3.5
3   Jack Matthews    Superman Returns     5.0
4   Jack Matthews  The Night Listener     3.0
5    Mick LaSalle   Lady in the Water     3.0
6    Mick LaSalle   Snakes on a Plane     4.0
7    Mick LaSalle        Just My Luck     2.0
8    Mick LaSalle    Superman Returns     3.0
9    Mick LaSalle  The Night Listener     3.0
10   Claudia Puig   Snakes on a Plane     3.5
11   Claudia Puig        Just My Luck     3.0
12   Claudia Puig  The Night Listener     4.5
13      Lisa Rose   Lady in the Water     2.5
14      Lisa Rose   Snakes on a Plane     3.5
15      Lisa Rose        Just My Luck     3.0
16      Lisa Rose    Superman Returns     3.5
17      Lisa Rose  The Night Listener     3.0
18      Lisa Rose   You Me and Dupree     2.5
19           Toby   Snakes on a Plane     4.5
20           Toby    Superman Returns     4.0
21   Gene Seymour   Lady in the Water     3.0
22   Gene Seymour   Snakes on a Plane     3.5
23   Gene Seymour   You Me and Dupree     3.5
24   Gene Seymour  The Night Listener     3.0

In [15]:
matrix.groupby(["source","target"])["rating"].sum()

source         target            
Claudia Puig   Just My Luck          3.0
               Snakes on a Plane     3.5
               The Night Listener    4.5
Gene Seymour   Lady in the Water     3.0
               Snakes on a Plane     3.5
               The Night Listener    3.0
               You Me and Dupree     3.5
Jack Matthews  Lady in the Water     3.0
               Snakes on a Plane     4.0
               Superman Returns      5.0
               The Night Listener    3.0
               You Me and Dupree     3.5
Lisa Rose      Just My Luck          3.0
               Lady in the Water     2.5
               Snakes on a Plane     3.5
               Superman Returns      3.5
               The Night Listener    3.0
               You Me and Dupree     2.5
Mick LaSalle   Just My Luck          2.0
               Lady in the Water     3.0
               Snakes on a Plane     4.0
               Superman Returns      3.0
               The Night Listener    3.0
Toby           Snakes o

In [17]:
matrix.groupby(["source","target"])["rating"].sum().unstack().fillna(0)

target         Just My Luck  Lady in the Water  Snakes on a Plane  \
source                                                              
Claudia Puig            3.0                0.0                3.5   
Gene Seymour            0.0                3.0                3.5   
Jack Matthews           0.0                3.0                4.0   
Lisa Rose               3.0                2.5                3.5   
Mick LaSalle            2.0                3.0                4.0   
Toby                    0.0                0.0                4.5   

target         Superman Returns  The Night Listener  You Me and Dupree  
source                                                                  
Claudia Puig                0.0                 4.5                0.0  
Gene Seymour                0.0                 3.0                3.5  
Jack Matthews               5.0                 3.0                3.5  
Lisa Rose                   3.5                 3.0                2.5  
Mick LaSalle                3.0                 3.0                0.0  
Toby                        4.0                 0.0                0.0

In [22]:
def get_rating_matrix(filename):
    matrix = pd.read_csv(filename)
    return matrix.groupby(["source","target"])["rating"].sum().unstack().fillna(0).values

In [23]:
get_rating_matrix("movie_rating.csv")

array([[3. , 0. , 3.5, 0. , 4.5, 0. ],
       [0. , 3. , 3.5, 0. , 3. , 3.5],
       [0. , 3. , 4. , 5. , 3. , 3.5],
       [3. , 2.5, 3.5, 3.5, 3. , 2.5],
       [2. , 3. , 4. , 3. , 3. , 0. ],
       [0. , 0. , 4.5, 4. , 0. , 0. ]])

In [24]:
freq = pd.read_csv('./1000i.csv')
freq

source  target
0          3       7
1          4      15
2          2      49
3          5      44
4          1       1
...      ...     ...
3211       5      35
3212       2       3
3213       4      15
3214       3      47
3215       3      34

[3216 rows x 2 columns]

In [25]:
freq["rating"] = 1
freq

source  target  rating
0          3       7       1
1          4      15       1
2          2      49       1
3          5      44       1
4          1       1       1
...      ...     ...     ...
3211       5      35       1
3212       2       3       1
3213       4      15       1
3214       3      47       1
3215       3      34       1

[3216 rows x 3 columns]

In [29]:
freq.groupby(["source", "target"])["rating"].sum().unstack().values

array([[19, 17, 14, 11, 17, 25,  7, 22,  5, 18, 10, 13, 13,  8, 20, 10,
         9, 10, 16, 15,  9, 11, 17, 15, 14,  8,  6, 12, 18, 12,  6, 18,
         9, 24,  7, 19, 14,  6,  4, 12, 15, 14, 20,  9, 12, 16, 11,  9,
        11, 12],
       [20, 16, 10, 15, 17, 18, 10, 13,  5, 19,  8, 14, 14,  9, 15, 14,
        13,  8, 12,  9,  5, 10, 28, 18,  7,  8,  6, 19, 14, 13, 11, 12,
        18, 15,  7, 11, 17,  9,  5,  5, 13, 12, 15,  9, 13, 16, 16, 10,
        16,  9],
       [12, 16, 13, 19, 23, 19,  5, 14,  5, 18,  7,  6, 14,  8, 20, 17,
        14, 11, 16, 12,  7,  9, 23, 12, 12,  8,  7, 23, 26, 10,  9, 20,
        16, 11,  4, 19, 12, 12,  5, 10, 10, 14, 10, 17, 15, 16, 11, 17,
         9, 11],
       [14, 14, 19, 11, 11, 18,  7, 16,  7, 17,  6, 19, 18, 12, 13, 13,
        14,  9, 21, 16,  6,  6, 19, 14, 19,  5, 12, 14, 18, 11, 11, 21,
        15, 10, 11, 14, 17, 21,  6, 14,  9, 16, 18, 12, 16, 16, 26, 16,
        12, 20],
       [13,  7,  8, 15, 13, 16,  3, 19, 11, 12,  7, 10, 13, 14, 16, 

In [32]:
def get_frequent_matrix(filename):
    freq = pd.read_csv(filename)
    freq["rating"] = 1
    return freq.groupby(["source", "target"])["rating"].sum().unstack().values

In [33]:
get_frequent_matrix("1000i.csv")

array([[19, 17, 14, 11, 17, 25,  7, 22,  5, 18, 10, 13, 13,  8, 20, 10,
         9, 10, 16, 15,  9, 11, 17, 15, 14,  8,  6, 12, 18, 12,  6, 18,
         9, 24,  7, 19, 14,  6,  4, 12, 15, 14, 20,  9, 12, 16, 11,  9,
        11, 12],
       [20, 16, 10, 15, 17, 18, 10, 13,  5, 19,  8, 14, 14,  9, 15, 14,
        13,  8, 12,  9,  5, 10, 28, 18,  7,  8,  6, 19, 14, 13, 11, 12,
        18, 15,  7, 11, 17,  9,  5,  5, 13, 12, 15,  9, 13, 16, 16, 10,
        16,  9],
       [12, 16, 13, 19, 23, 19,  5, 14,  5, 18,  7,  6, 14,  8, 20, 17,
        14, 11, 16, 12,  7,  9, 23, 12, 12,  8,  7, 23, 26, 10,  9, 20,
        16, 11,  4, 19, 12, 12,  5, 10, 10, 14, 10, 17, 15, 16, 11, 17,
         9, 11],
       [14, 14, 19, 11, 11, 18,  7, 16,  7, 17,  6, 19, 18, 12, 13, 13,
        14,  9, 21, 16,  6,  6, 19, 14, 19,  5, 12, 14, 18, 11, 11, 21,
        15, 10, 11, 14, 17, 21,  6, 14,  9, 16, 18, 12, 16, 16, 26, 16,
        12, 20],
       [13,  7,  8, 15, 13, 16,  3, 19, 11, 12,  7, 10, 13, 14, 16, 